name: Release

on:
  push:
    branches: ['main']
    tags: ['v*', 'latest']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Docker tag
        id: set-docker-tag
        run: |
          # If the Git ref name starts with "v", remove that "v" to make the CLEAN_TAG
          if [[ "${GITHUB_REF_NAME}" == v* ]]; then
            CLEAN_TAG="${GITHUB_REF_NAME#v}"
            echo "IMAGE_TAG=${CLEAN_TAG}" >> $GITHUB_ENV
          else
            # If it's not a v-tag, use tag label as-is
            echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/solarrepublic/cosmos-sync-balancer:latest
            ghcr.io/solarrepublic/cosmos-sync-balancer:${{ env.IMAGE_TAG }}
